services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: miappdb
      MYSQL_USER: miappuser
      MYSQL_PASSWORD: miapppassword
    ports:
      - "3307:3306"  # Cambiar a puerto estándar
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 30s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password --skip-name-resolve --explicit_defaults_for_timestamp=1

  api:
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile
    container_name: club-key-api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=miappdb;User=miappuser;Password=miapppassword;Pooling=True;Max Pool Size=100;Connection Timeout=60;"
    ports:
      - "5006:8080"

volumes:
  mysql_data: